_wandb:
    value:
        cli_version: 0.23.0
        e:
            22hcdsz5hr1bhtwz6t86pfbb46dda5v1:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "4294967296"
                args:
                    - train
                    - --wandb
                codePath: .venv/bin/bsort
                codePathLocal: .venv/bin/bsort
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "994662584320"
                        used: "579122651136"
                email: dhafindra.razaqa@gmail.com
                executable: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier/.venv/bin/python3.13
                git:
                    commit: 4063d8e76fb44af4d56cd5fd5cb127a9cc74ab97
                    remote: https://github.com/DhafindraStefano/bottlecap-sorter.git
                host: Dhafindras-MacBook-Pro.local
                memory:
                    total: "25769803776"
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier/.venv/bin/bsort
                python: CPython 3.13.3
                root: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier
                startedAt: "2025-11-25T14:34:38.095749Z"
                writerId: 22hcdsz5hr1bhtwz6t86pfbb46dda5v1
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 16
            "4": 3.13.3
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
model:
    value: ColorThreshold
test_size:
    value: 0.2
