_wandb:
  value:
    cli_version: 0.23.0
    e:
      himbj35krvihr1ccdy0oyjjc9fp7bayj:
        codePath: verify_wandb.py
        codePathLocal: verify_wandb.py
        email: dhafindra.razaqa@gmail.com
        executable: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier/.venv/bin/python
        git:
          commit: 4063d8e76fb44af4d56cd5fd5cb127a9cc74ab97
          remote: https://github.com/DhafindraStefano/bottlecap-classifier.git
        host: Dhafindras-MacBook-Pro.local
        os: macOS-26.1-arm64-arm-64bit-Mach-O
        program: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier/verify_wandb.py
        python: CPython 3.13.3
        root: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier
        startedAt: "2025-11-25T13:51:51.495873Z"
        writerId: himbj35krvihr1ccdy0oyjjc9fp7bayj
    m: []
    python_version: 3.13.3
    t:
      "3":
        - 2
      "4": 3.13.3
      "5": 0.23.0
      "12": 0.23.0
      "13": darwin-arm64
