_wandb:
    value:
        cli_version: 0.23.0
        e:
            i87qb25790kn37spdulx1xodb8bkhjds:
                args:
                    - train
                    - --wandb
                codePath: .venv/bin/bsort
                codePathLocal: .venv/bin/bsort
                email: dhafindra.razaqa@gmail.com
                executable: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier/.venv/bin/python3.13
                git:
                    commit: 0d0ba47c3702ef02786615d1b869315aa7abb88c
                    remote: https://github.com/DhafindraStefano/bottlecap-sorter.git
                host: Dhafindras-MacBook-Pro.local
                os: macOS-26.1-arm64-arm-64bit-Mach-O
                program: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier/.venv/bin/bsort
                python: CPython 3.13.3
                root: /Users/drstefano/Documents/Work/Technical Tests/bottlecap-classifier
                startedAt: "2025-11-25T15:02:25.312447Z"
                writerId: i87qb25790kn37spdulx1xodb8bkhjds
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 16
            "4": 3.13.3
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
model:
    value: ColorThreshold
test_size:
    value: 0.2
